services:
  rabbitmq:
    image: rabbitmq:3.13
    restart: always
    networks:
      - test_net

  location_storage:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
        - test_net

  location_producer:
    image: "golang:1.22.5"
    volumes:
      - ./:/app
    command:
      - bash
      - -c
      - |
        set -e
        cd /app
        go run . producer
    networks:
      - test_net

  location_writer:
    image: "golang:1.22.5"
    volumes:
      - ./:/app
    environment:
      DATABASE_HOST: location_storage
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: example
      DATABASE_DBNAME: postgres
    command:
      - bash
      - -c
      - |
        set -e
        cd /app
        go run . writer    
    networks:
      - test_net

  location_analyser:
    image: "golang:1.22.5"
    environment:
      DATABASE_HOST: location_storage
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: example
      DATABASE_DBNAME: postgres
    volumes:
      - ./:/app
    command:
      - bash
      - -c
      - |
        set -e
        cd /app
        go run . analyser
    networks:
      - test_net

  test_suite:
    image: "golang:1.22.5"
    volumes:
      - ./:/app
    command:
      - bash
      - -c
      - |
        set -e
        cd /app
        go test -v ./...
    networks:
      - test_net

networks:
  test_net:
